"""audio-minutes の版付き契約と共有アダプター。"""

from audio_minutes_contracts.models import (
    ApiError,
    ApiErrorBody,
    Backend,
    ErrorCode,
    FormatProfile,
    FormatSection,
    InputKind,
    Job,
    JobFailure,
    JobInput,
    JobInputArtifact,
    JobKind,
    JobStatus,
    LanguageMode,
    MinutesJobSettings,
    MinutesVersion,
    Processing,
    ProcessingModel,
    RecordingPackage,
    RecordingSource,
    RecordingTrack,
    Resources,
    ReviewAttempt,
    ReviewItem,
    Segment,
    Session,
    SessionStatus,
    SessionTrack,
    Strategy,
    Timings,
    Transcript,
    TranscriptionJobSettings,
    TranscriptTrack,
    WorkerResult,
    WorkerResultArtifact,
)
from audio_minutes_contracts.schemas import SCHEMA_VERSIONS as _SCHEMA_VERSIONS

__all__ = [
    "ApiError",
    "ApiErrorBody",
    "Backend",
    "ErrorCode",
    "FormatProfile",
    "FormatSection",
    "InputKind",
    "Job",
    "JobFailure",
    "JobInput",
    "JobInputArtifact",
    "JobKind",
    "JobStatus",
    "LanguageMode",
    "MinutesJobSettings",
    "MinutesVersion",
    "Processing",
    "ProcessingModel",
    "RecordingPackage",
    "RecordingSource",
    "RecordingTrack",
    "Resources",
    "ReviewAttempt",
    "ReviewItem",
    "Segment",
    "Session",
    "SessionStatus",
    "SessionTrack",
    "Strategy",
    "Timings",
    "Transcript",
    "TranscriptTrack",
    "TranscriptionJobSettings",
    "WorkerResult",
    "WorkerResultArtifact",
]

# 契約の現行版は schemas.SCHEMA_VERSIONS が正。二重管理しない。
CONTRACT_VERSIONS = dict(_SCHEMA_VERSIONS)
