"""audio-minutes の版付き契約と共有アダプター。"""

from audio_minutes_contracts.models import (
    ApiError,
    ApiErrorBody,
    Backend,
    ErrorCode,
    FormatProfile,
    FormatSection,
    InputKind,
    Job,
    JobFailure,
    JobInput,
    JobInputArtifact,
    JobKind,
    JobStatus,
    LanguageMode,
    MinutesVersion,
    Processing,
    ProcessingModel,
    RecordingPackage,
    RecordingSource,
    RecordingTrack,
    Resources,
    ReviewAttempt,
    ReviewItem,
    Segment,
    Session,
    SessionStatus,
    SessionTrack,
    Strategy,
    Timings,
    Transcript,
    TranscriptTrack,
    WorkerResult,
    WorkerResultArtifact,
)

__all__ = [
    "ApiError",
    "ApiErrorBody",
    "Backend",
    "ErrorCode",
    "FormatProfile",
    "FormatSection",
    "InputKind",
    "Job",
    "JobFailure",
    "JobInput",
    "JobInputArtifact",
    "JobKind",
    "JobStatus",
    "LanguageMode",
    "MinutesVersion",
    "Processing",
    "ProcessingModel",
    "RecordingPackage",
    "RecordingSource",
    "RecordingTrack",
    "Resources",
    "ReviewAttempt",
    "ReviewItem",
    "Segment",
    "Session",
    "SessionStatus",
    "SessionTrack",
    "Strategy",
    "Timings",
    "Transcript",
    "TranscriptTrack",
    "WorkerResult",
    "WorkerResultArtifact",
]

CONTRACT_VERSIONS = {
    "recording-package": 1,
    "job": 1,
    "worker-result": 1,
    "transcript": 1,
    "minutes-version": 1,
    "format-profile": 1,
    "session": 1,
    "error": 1,
}
